---
title: "intro to R"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(plotly)
```

```{r health}

health_full <- read_csv("https://chronicdata.cdc.gov/api/views/cwsq-ngmh/rows.csv?accessType=DOWNLOAD")

health_ca <- filter(health_full, StateAbbr == "CA")

```

```{r electric}

pge_20_q1_elec <- read_csv("PGE_2020_Q1_ElectricUsageByZip.csv")

write_csv(health_ca, "health_ca.csv")

saveRDS(health_ca, "health_ca.rds")

save(health_ca, pge_20_q1_elec, file = "working_datasets.rda")
load("working_datasets.rda")

# -----
# LOOPS

year <- 2020
quarters <- 1:4
type <- "Electric"

pge_20_elec <- NULL

for(quarter in quarters) {
  
  filename <- 
    paste0(
      "PGE_",
      year,
      "_Q",
      quarter,
      "_",
      type,
      "UsageByZip.csv"
    )

  print(filename)
  
  temp <- read_csv(filename)
  
  pge_20_elec <- rbind(pge_20_elec,temp)
  # Note rbind requires field names to be consistent for every new thing that you add.

  saveRDS(pge_20_elec, "pge_20_elec.rds")
}

# -----
# more filtering n stuff

pge_filter <- filter(pge_20_elec, CUSTOMERCLASS %in% c("Elec- Residential","Elec- Commercial"))

pge_select <-
  select(
    pge_filter,
    -c(YEAR, COMBINED, AVERAGEKWH)
  )

```